services:
  nginx:
    build:
      context: ./docker
      dockerfile: nginx/Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./:/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
